# @name ping

GET http://localhost:3000/ping

###

# @name register

POST http://localhost:3000/register
Accept: application/json
Content-Type: application/json

{
    "email": "crashTestDummy@test.com",
    "password": "thermostatdonationbarndiamond"
}

###

# @name login
POST http://localhost:3000/login
Accept: application/json
Content-Type: application/json

{
    "email": "crashTestDummy@test.com",
    "password": "thermostatdonationbarndiamond"
}

###

# @name profile
GET http://localhost:3000/profile
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name permanently delete user
GET http://localhost:3000/deleteaccount
Cookie: {{login.response.headers.Set-Cookie}}

###

# @name update
POST http://localhost:3000/updateuser
Cookie: {{login.response.headers.Set-Cookie}}
Accept: application/json
Content-Type: application/json

{
    "email": "crashTestDummy22@test.com",
    "password": "thermostatdonationbarndiamond22"
}

###

# @name logout
POST http://localhost:3000/logout
Cookie: {{login.response.headers.Set-Cookie}}
Accept: application/json

###

# @name logouteverywhere
# @name logout
POST http://localhost:3000/logouteverywhere
Cookie: {{login.response.headers.Set-Cookie}}
Accept: application/json
###

